### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by itshnawy** [itshnawy/FriendsClips#1]
- [ ] Create a Simple design: video player on the middle of the page and Session or Ep 
- [ ] Friends Clips Data: get it from youtube and create a json file with all of them
- [ ] Choosing System: random video id number using Math.random()
- [ ] Stick to the name or choose another name
- [ ] Publish it
